baseURL = "https://wenchao.ren"
languageCode = "zh-cn"
title = "被遗忘的博客"
theme = "zozo"
disqusShortname = "rollenholt"  ## disqus配置
publishDir = "docs"  ##生成内容的目录，从public改为docs。因为GitHub pages好像只能选这个


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "xkrivzooh"
  authorlocation = "BeiJing, China"
  email = "me@wenchao.ren"
  githubName = "xkrivzooh"
  hjsStyle = "idea"
  #subTitle = "the site subtitle"                                       # site's subTitle  # 网站二级标题
  #footerSlogan = "My spiritual home"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["JAVA","Spring","IOT", "KAFKA", "python", "mysql"]                                  # site's keywords  # 网站关键字
  description = "被遗忘的博客"                        # site's description  # 网站描述
  enableMathJax = false                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = false                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]


[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/archives/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[permalinks]
  post = "/:year/:month/:title/"

# Your socail's url
[social]
  github = "https://github.com/xkrivzooh"
  weibo = "https://weibo.com/AnotherRobot/home"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

  [markup.highlight]
    codeFences = false
    guessSyntax = true
    noClasses = true
    lineNoStart = 1
    anchorLineNos = true
    tabWidth = 4
    lineNumbersInTable = true
    lineNos = true
    style = "github"

